from __future__ import annotations

import logging
import shlex
import sys
import time
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

from .adb import AdbClient
from .planner import RestorePlan
from .restore_state import RestoreState
from .runner import SnaptoolAbortedError
from .tar_index import TarIndex


# Appops whose mode is owned by a runtime permission. On Android 11+ the
# AppOpsService policy refuses (or just ignores) direct `cmd appops set`
# calls for these — the appop is automatically updated when the underlying
# `pm grant`/`pm revoke` runs. Setting them via `cmd appops set` is at best
# a redundant no-op and at worst contributes to AppOpsService contention
# during system_server boot (where PermissionPolicyService is already
# replaying the same sync internally, and on some Android versions the
# resulting RuntimeExceptions stall the service). We skip them entirely
# in `_apply_runtime_state` and let `pm grant` handle the appop side.
_RUNTIME_PERMISSION_BACKED_APPOPS = frozenset({
    # Location
    "COARSE_LOCATION", "FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION",
    # Contacts
    "READ_CONTACTS", "WRITE_CONTACTS",
    # Phone / Call Log
    "READ_CALL_LOG", "WRITE_CALL_LOG", "PROCESS_OUTGOING_CALLS",
    "CALL_PHONE", "ANSWER_PHONE_CALLS",
    "READ_PHONE_STATE", "READ_PHONE_NUMBERS",
    "ADD_VOICEMAIL", "USE_SIP", "ACCEPT_HANDOVER",
    # Calendar
    "READ_CALENDAR", "WRITE_CALENDAR",
    # SMS
    "READ_SMS", "RECEIVE_SMS", "RECEIVE_MMS", "RECEIVE_WAP_PUSH",
    "SEND_SMS", "READ_CELL_BROADCASTS",
    # Sensors / Activity
    "BODY_SENSORS", "BODY_SENSORS_BACKGROUND",
    "ACTIVITY_RECOGNITION",
    # Storage / Media
    "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE",
    "ACCESS_MEDIA_LOCATION",
    "READ_MEDIA_AUDIO", "READ_MEDIA_IMAGES", "READ_MEDIA_VIDEO",
    "READ_MEDIA_VISUAL_USER_SELECTED",
    # Camera / Microphone
    "CAMERA", "RECORD_AUDIO",
    # Bluetooth (Android 12+)
    "BLUETOOTH_SCAN", "BLUETOOTH_CONNECT", "BLUETOOTH_ADVERTISE",
    # WiFi (Android 13+)
    "NEARBY_WIFI_DEVICES",
    # Notifications (Android 13+)
    "POST_NOTIFICATION",
    # UWB / Ranging (Android 14+)
    "RANGING", "UWB_RANGING",
    # Health Connect (Android 14+)
    "READ_HEART_RATE", "READ_OXYGEN_SATURATION", "READ_SKIN_TEMPERATURE",
})

# Pause between packages in `_apply_runtime_state`. After applying ~20-30
# adb calls for one package (force-stop, appops reset, perm grants/revokes,
# non-runtime-perm appops), give AppOpsService a beat to settle before
# the next package's flood. Cheap insurance against accumulating contention
# pressure on slower devices / preview builds. Total overhead for ~12
# packages is ~1.2s.
_RUNTIME_STATE_INTER_PACKAGE_DELAY_S = 0.1

# CrashRecovery / PackageWatchdog boot-loop counter properties.
#
# PackageWatchdog.BootThreshold counts SYSTEM_RESTART events generated by
# `setprop ctl.stop zygote` against a hardcoded threshold of 5 events in
# 10 minutes. Trip the threshold and Android escalates through rescue
# levels (ALL_DEVICE_CONFIG_RESET → WARM_REBOOT → RESET_SETTINGS_* →
# FACTORY_RESET), with the escalation state persisted across reboots in
# /metadata/watchdog/mitigation_count.txt. A secondary trigger condition
# (`performedMitigationsDuringWindow() && count > 1`) means once a device
# is at mitigation-count > 0, just 2 boot events trip it again.
#
# The threshold field (`mBootTriggerCount=5`) is `final` and not
# runtime-mutable. But the COUNTER and window-start are stored in two
# system properties that PackageWatchdog reads fresh on every event (no
# caching) via CrashRecoveryProperties.rescueBootCount() / rescueBootStart().
# Both have SELinux type crashrecovery_prop and are writable from a root
# shell.
#
# Our defense: write `count=0; start=0` ATOMICALLY in the same root shell
# script that issues `ctl.stop zygote`. Because the new system_server
# (and its PackageWatchdog) doesn't exist yet at that moment, nothing
# can race the setprop. When zygote restarts and the new system_server's
# noteBoot() runs, it reads start=0 → `now - 0 > 10-min trigger window`
# → takes the reset branch (`setCount(1); setStart(now); return false`)
# → never reaches the count++ branch that could trip. We also reset 0/0
# again after framework-ready as defense in depth.
#
# An earlier design captured the prop values before stopping zygote and
# wrote them back after framework-ready ("rewind"). That looked correct
# but failed empirically: PackageWatchdog's `setStart(uptimeMillis)` in
# the new system_server could lag past our rewind (the AOSP write isn't
# tightly synchronized with onBootPhase(BOOT_COMPLETED), which is what
# our framework-ready check waits for). Once start landed at "recent
# uptime", every subsequent restart took the count++ branch and count
# grew by 1 per restore. See snapshots/two/logs/restore-thirdparty.log
# from 2026-05-19 11:01-11:03 for the empirical trace.
_RESCUE_BOOT_COUNT_PROP = "crashrecovery.rescue_boot_count"
_RESCUE_BOOT_START_PROP = "crashrecovery.rescue_boot_start"


@dataclass(frozen=True)
class ExecConfig:
    chunk_size: int = 120
    runtime_state_batch_size_path: int = 24
    runtime_state_batch_size_app: int = 0
    sdk_version: int | None = None


class RestoreExecutor:
    def __init__(self, adb: "AdbClient", logger: logging.Logger, exec_cfg: ExecConfig):
        self.adb = adb
        self.logger = logger
        self.cfg = exec_cfg

    @staticmethod
    def _parse_uid_pkg_from_path(p: str):
        import re
        m = re.match(r"^data/user/(\d+)/([^/]+)$", p)
        if m:
            return int(m.group(1)), m.group(2)
        m = re.match(r"^data/user_de/(\d+)/([^/]+)$", p)
        if m:
            return int(m.group(1)), m.group(2)
        m = re.match(r"^data/media/(\d+)/Android/data/([^/]+)$", p)
        if m:
            return int(m.group(1)), m.group(2)
        m = re.match(r"^data/media/(\d+)/Android/media/([^/]+)$", p)
        if m:
            return int(m.group(1)), m.group(2)
        m = re.match(r"^data/media/(\d+)/Android/obb/([^/]+)$", p)
        if m:
            return int(m.group(1)), m.group(2)
        return None

    @staticmethod
    def _is_media_root_allow_empty(p: str) -> bool:
        return bool(__import__("re").match(r"^data/media/\d+/(DCIM|Pictures)$", p))

    @staticmethod
    def _build_pkg_roots(uid: int, pkg: str) -> list[str]:
        return [
            f"data/user/{uid}/{pkg}",
            f"data/user_de/{uid}/{pkg}",
            f"data/media/{uid}/Android/data/{pkg}",
            f"data/media/{uid}/Android/media/{pkg}",
            f"data/media/{uid}/Android/obb/{pkg}",
        ]

    def _safe_media_refresh(self, plan: "RestorePlan") -> None:
        self.logger.info("Post-restore: safe media refresh (Android 13) ...")
        lines = ["su", "set -e", ""]

        for uid in plan.user_ids:
            lines += [
                f"am force-stop --user {uid} com.android.providers.media >/dev/null 2>&1 || true",
                f"am force-stop --user {uid} {shlex.quote(plan.photos_pkg)} >/dev/null 2>&1 || true",
                f"rm -rf /data/media/{uid}/DCIM/.thumbnails >/dev/null 2>&1 || true",
                f"rm -rf /data/media/{uid}/Pictures/.thumbnails >/dev/null 2>&1 || true",
                f"rm -rf /data/media/{uid}/.thumbnails >/dev/null 2>&1 || true",
                f"restorecon -RF /data/media/{uid} >/dev/null 2>&1 || true",
            ]

        lines += [
            "",
            "if cmd media_store >/dev/null 2>&1; then",
            "  cmd media_store scan --volume external >/dev/null 2>&1 || true",
            "fi",
            "",
            "monkey -p com.android.providers.media 1 >/dev/null 2>&1 || true",
            "exit",
            "exit",
            "",
        ]
        self.adb.shell_script(
            "\n".join(lines),
            critical=False,
            phase="restore: media refresh",
        )

    def _reset_rescue_counter(self) -> None:
        """Write `crashrecovery.rescue_boot_count=0` and `…_start=0`.

        Called twice per restore: once atomically with the zygote stop
        (see `_stop_framework_best_effort`) — that's the load-bearing
        one — and once again after framework-ready, as defense in depth
        so the device's boot-loop state stays clean between our restores.

        Best-effort: never raises.
        """
        script = (
            "su\n"
            f"setprop {_RESCUE_BOOT_COUNT_PROP} 0\n"
            f"setprop {_RESCUE_BOOT_START_PROP} 0\n"
            "exit\nexit\n"
        )
        try:
            self.adb.shell_script(
                script,
                critical=False,
                phase="restore: rescue-counter reset",
            )
        except SnaptoolAbortedError as exc:
            self.logger.warning(
                "[rescue-counter] reset failed (continuing): %s", exc,
            )
            return
        except Exception as exc:
            self.logger.warning(
                "[rescue-counter] reset failed unexpectedly (continuing): %s", exc,
            )
            return
        self.logger.info("[rescue-counter] reset to count=0 start=0")

    def _stop_framework_best_effort(self) -> None:
        """Stop the Android framework, atomically resetting the
        CrashRecovery boot-loop counter properties to 0/0 in the SAME
        root shell script. The reset must happen here (not in a separate
        adb call) so PackageWatchdog's noteBoot in the next system_server
        cannot race us — at the moment we write the setprop, the OLD
        system_server is about to be killed and the NEW one doesn't
        exist yet, so no PackageWatchdog instance is running."""
        self.logger.info("Stopping framework (best-effort) ...")
        self.adb.shell_script(
            "su\n"
            f"setprop {_RESCUE_BOOT_COUNT_PROP} 0\n"
            f"setprop {_RESCUE_BOOT_START_PROP} 0\n"
            "if command -v stop >/dev/null 2>&1; then stop; "
            "elif command -v setprop >/dev/null 2>&1; then "
            "setprop ctl.stop zygote 2>/dev/null || true; "
            "setprop ctl.stop zygote_secondary 2>/dev/null || true; "
            "fi\n"
            "exit\nexit\n",
            critical=False,
            phase="restore: stop framework",
        )

    def _start_framework_best_effort(self) -> None:
        self.logger.info("Starting framework (best-effort) ...")
        self.adb.shell_script(
            "su\n"
            "if command -v start >/dev/null 2>&1; then start; "
            "elif command -v setprop >/dev/null 2>&1; then "
            "setprop ctl.start zygote 2>/dev/null || true; "
            "setprop ctl.start zygote_secondary 2>/dev/null || true; "
            "fi\n"
            "sleep 2\n"
            "exit\nexit\n",
            critical=False,
            phase="restore: start framework",
        )

    @contextmanager
    def _framework_stopped(self):
        """Stop the Android framework, run the body, then ALWAYS restart.

        If the body raises (e.g. a critical adb call aborts mid-restore), the
        restart still runs in a `finally` so we don't leave the device with
        zygote dead. A failure of the restart itself is logged loudly but
        swallowed, so it doesn't mask the original error.

        Also verifies root remains available at both transitions. On some
        Magisk setups, magiskd can die alongside zygote during framework
        stop and not come back cleanly after restart — without the check
        the body would silently no-op via the `|| true` pattern in every
        shell script and the tool would falsely report success.

        The zygote stop atomically resets the CrashRecovery boot-loop
        counter to 0/0 (see _stop_framework_best_effort). After the new
        framework comes up, we reset again as defense in depth, so the
        device's state stays clean between our restores too.
        """
        self._stop_framework_best_effort()
        try:
            # Root must still work for the body (extract, swap DBs, etc.).
            # If this raises, the finally below still attempts restart.
            self.adb.ensure_root(phase="restore: root check after framework stop")
            yield
        finally:
            # Nested try/finally so the rescue-counter reset ALWAYS runs,
            # even if a post-restart check below re-raises mid-finally.
            try:
                try:
                    self._start_framework_best_effort()
                except SnaptoolAbortedError as exc:
                    self.logger.error(
                        "FRAMEWORK RESTART FAILED after restore exit; "
                        "device may not boot until manual reboot. (%s)",
                        exc,
                    )
                except Exception as exc:
                    self.logger.error(
                        "FRAMEWORK RESTART FAILED (unexpected) after restore exit; "
                        "device may not boot until manual reboot. (%s)",
                        exc,
                    )
                # Post-restart root check. If the body raised, only LOG so we
                # don't mask the original exception. If the body succeeded,
                # raise — root being gone post-restart means subsequent
                # post-restore fixups (perms, appops, restorecon) would
                # silently fail; better to surface that as an abort.
                body_already_raised = sys.exc_info()[0] is not None
                try:
                    self.adb.ensure_root(phase="restore: root check after framework restart")
                except SnaptoolAbortedError as exc:
                    if body_already_raised:
                        self.logger.error(
                            "ROOT UNAVAILABLE after framework restart (also): %s. "
                            "Post-restore fixups cannot run on this device.",
                            exc,
                        )
                    else:
                        raise
                except Exception as exc:
                    self.logger.error(
                        "ROOT CHECK FAILED unexpectedly after framework restart: %s",
                        exc,
                    )

                # Framework-services-ready check. `ensure_root` only verifies
                # `su -c id` works; system_server can still be booting and not
                # publishing PMS/AMS/AppOpsService. If we return now, the
                # caller's post-stage runtime state replay would flood a
                # not-yet-ready system_server and trigger crash cycles. Block
                # here until services answer, or abort if they don't.
                body_already_raised = sys.exc_info()[0] is not None
                try:
                    self.adb.ensure_framework_ready(
                        phase="restore: framework-ready after restart",
                    )
                except SnaptoolAbortedError as exc:
                    if body_already_raised:
                        self.logger.error(
                            "FRAMEWORK NOT READY after restart (also): %s. "
                            "Post-stage runtime state cannot be applied cleanly.",
                            exc,
                        )
                    else:
                        raise
                except Exception as exc:
                    self.logger.error(
                        "FRAMEWORK-READY CHECK FAILED unexpectedly after framework restart: %s",
                        exc,
                    )
            finally:
                # Defense-in-depth post-ready reset. The new system_server
                # has now run noteBoot() which likely wrote count=1 and
                # start=now (reset branch, since our pre-stop reset set
                # start=0). Overwrite back to 0/0 so the device sits idle
                # between restores in a "fresh window" state.
                self._reset_rescue_counter()

    def _restart_keystore_safety_net(self) -> None:
        """Best-effort, swallow-all restart of keystore2/credstore. Used inside
        a finally on the keystore swap scripts: if the swap script aborted
        mid-stream (transport drop after stop, before start), the in-script
        restart never ran. We try once more here over a fresh adb call."""
        try:
            self.adb.shell_script(
                "su\n"
                "if command -v start >/dev/null 2>&1; then\n"
                "  start keystore2 >/dev/null 2>&1 || true\n"
                "  start credstore >/dev/null 2>&1 || true\n"
                "fi\n"
                "if command -v setprop >/dev/null 2>&1; then\n"
                "  setprop ctl.start keystore2 >/dev/null 2>&1 || true\n"
                "  setprop ctl.start credstore >/dev/null 2>&1 || true\n"
                "fi\n"
                "exit\nexit\n",
                critical=False,
                phase="restore: keystore restart safety net",
            )
        except SnaptoolAbortedError as exc:
            self.logger.error(
                "KEYSTORE RESTART FAILED after restore exit; accounts/keystore "
                "may be inaccessible until reboot. (%s)",
                exc,
            )
        except Exception as exc:
            self.logger.error(
                "KEYSTORE RESTART FAILED (unexpected) after restore exit; "
                "accounts/keystore may be inaccessible until reboot. (%s)",
                exc,
            )

    # Substrings in stderr that indicate system_server (or a service it owns)
    # is unavailable to a `cmd`/`pm`/`am` call. When we see this mid-replay,
    # we MUST stop hammering — every subsequent call will worsen the cascade
    # and risks tripping the kernel watchdog into a full device reboot.
    _SVC_UNAVAILABLE_MARKERS = ("Can't find service:", "Can not find service")

    def _replay_adb_call(self, args: list[str]) -> "CmdResult":
        """Run a non-critical adb call from `_apply_runtime_state`, with an
        in-flight circuit breaker.

        If the call returns `Can't find service: X` in stderr, system_server
        is unavailable. Continuing the flood at this point is what triggers
        the watchdog cascade. We pause and call `ensure_framework_ready` —
        which either waits for system_server to publish its services again
        (transient hiccup; we resume the replay), or times out and raises
        `SnaptoolAbortedError` (the restore aborts cleanly, marker is
        retained, queue runner picks up via `recover-thirdparty`).
        """
        res = self.adb.adb(args, check=False)
        if (
            res.rc != 0
            and res.stderr
            and any(m in res.stderr for m in self._SVC_UNAVAILABLE_MARKERS)
        ):
            stderr_first = res.stderr.strip().splitlines()[0][:160]
            self.logger.warning(
                "[runtime-state] system-service unavailable mid-replay "
                "(stderr: %s); pausing for system_server to recover ...",
                stderr_first,
            )
            self.adb.ensure_framework_ready(
                phase="restore: framework-ready during runtime state replay",
            )
            self.logger.info(
                "[runtime-state] system_server recovered; resuming replay."
            )
        return res

    def _apply_runtime_state(
        self,
        runtime_state: dict,
        package_batch_size: int = 1,
        apply_revokes: bool = False,
    ) -> None:
        if not runtime_state:
            return
        packages = [(pkg, user_map) for pkg, user_map in runtime_state.items() if isinstance(pkg, str) and isinstance(user_map, dict)]
        if not packages:
            return

        total = len(packages)
        if package_batch_size <= 0 or package_batch_size > total:
            package_batch_size = total
        total_batches = (total + package_batch_size - 1) // package_batch_size
        self.logger.info(
            "Applying package runtime state (permissions/appops): %d packages in %d batch(es) ...",
            total,
            total_batches,
        )

        for batch_i, start in enumerate(range(0, total, package_batch_size), start=1):
            chunk = packages[start:start + package_batch_size]
            self.logger.info(
                "Applying runtime state batch %d/%d (%d packages) ...",
                batch_i,
                total_batches,
                len(chunk),
            )
            for idx, (pkg, user_map) in enumerate(chunk, start=start + 1):
                self.logger.info("Applying runtime state for package %d/%d: %s", idx, total, pkg)
                for uid_s, state in user_map.items():
                    try:
                        uid = int(uid_s)
                    except Exception:
                        continue
                    if not isinstance(state, dict):
                        continue

                    uid_s_arg = str(uid)
                    self._replay_adb_call(["shell", "am", "force-stop", "--user", uid_s_arg, pkg])
                    self._replay_adb_call(["shell", "cmd", "appops", "reset", "--user", uid_s_arg, pkg])

                    perms = state.get("runtime_permissions")
                    if isinstance(perms, dict):
                        for perm, granted in perms.items():
                            if not isinstance(perm, str):
                                continue
                            if isinstance(granted, bool):
                                if granted:
                                    self._replay_adb_call(["shell", "pm", "grant", "--user", uid_s_arg, pkg, perm])
                                elif apply_revokes:
                                    self._replay_adb_call(["shell", "pm", "revoke", "--user", uid_s_arg, pkg, perm])
                            elif granted:
                                self._replay_adb_call(["shell", "pm", "grant", "--user", uid_s_arg, pkg, perm])
                    elif isinstance(perms, list):
                        for perm in perms:
                            if not isinstance(perm, str):
                                continue
                            self._replay_adb_call(["shell", "pm", "grant", "--user", uid_s_arg, pkg, perm])

                    appops = state.get("appops")
                    if isinstance(appops, dict):
                        skipped_rt = 0
                        for op, mode in appops.items():
                            if not isinstance(op, str) or not isinstance(mode, str):
                                continue
                            if op in _RUNTIME_PERMISSION_BACKED_APPOPS:
                                # AppOps tied to runtime permissions are set
                                # automatically by `pm grant/revoke` above.
                                # `cmd appops set` for these is either silently
                                # ignored (same-uid) or rejected with
                                # RuntimeException (cross-uid) on modern
                                # Android — wasted call + AppOpsService load.
                                skipped_rt += 1
                                continue
                            self._replay_adb_call(
                                ["shell", "cmd", "appops", "set", "--user", uid_s_arg, pkg, op, mode],
                            )
                        if skipped_rt:
                            self.logger.debug(
                                "[runtime-state] %s: skipped %d runtime-perm-backed appops "
                                "(handled via pm grant/revoke)",
                                pkg, skipped_rt,
                            )

                # Brief throttle between packages — gives AppOpsService time
                # to drain its queue before the next package's flood.
                time.sleep(_RUNTIME_STATE_INTER_PACKAGE_DELAY_S)

    def _permission_state_file_fixups(self, user_ids: list[int]) -> None:
        self.logger.info("Post-restore: permission state file fixups ...")
        lines = ["su", "cd /", ""]

        lines += [
            "if [ -f /data/system/appops.xml ]; then",
            "  chown system:system /data/system/appops.xml >/dev/null 2>&1 || true",
            "  chmod 600 /data/system/appops.xml >/dev/null 2>&1 || true",
            "  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system/appops.xml >/dev/null 2>&1 || true; fi",
            "fi",
            "",
        ]

        for uid in user_ids:
            lines += [
                f"if [ -f /data/system/users/{uid}/runtime-permissions.xml ]; then",
                f"  chown system:system /data/system/users/{uid}/runtime-permissions.xml >/dev/null 2>&1 || true",
                f"  chmod 600 /data/system/users/{uid}/runtime-permissions.xml >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system/users/{uid}/runtime-permissions.xml >/dev/null 2>&1 || true; fi",
                "fi",
                "",
                f"if [ -f /data/system/users/{uid}/package-restrictions.xml ]; then",
                f"  chown system:system /data/system/users/{uid}/package-restrictions.xml >/dev/null 2>&1 || true",
                f"  chmod 660 /data/system/users/{uid}/package-restrictions.xml >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system/users/{uid}/package-restrictions.xml >/dev/null 2>&1 || true; fi",
                "fi",
                "",
                # Android 13+ permission module storage.
                f"if [ -f /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml ]; then",
                f"  chown system:system /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml >/dev/null 2>&1 || true",
                f"  chmod 600 /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml >/dev/null 2>&1 || true; fi",
                "fi",
                "",
                f"if [ -f /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml.reservecopy ]; then",
                f"  chown system:system /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml.reservecopy >/dev/null 2>&1 || true",
                f"  chmod 600 /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml.reservecopy >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/misc_de/{uid}/apexdata/com.android.permission/runtime-permissions.xml.reservecopy >/dev/null 2>&1 || true; fi",
                "fi",
                "",
                f"if [ -f /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml ]; then",
                f"  chown system:system /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml >/dev/null 2>&1 || true",
                f"  chmod 600 /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml >/dev/null 2>&1 || true; fi",
                "fi",
                "",
                f"if [ -f /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml.reservecopy ]; then",
                f"  chown system:system /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml.reservecopy >/dev/null 2>&1 || true",
                f"  chmod 600 /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml.reservecopy >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/misc_de/{uid}/apexdata/com.android.permission/roles.xml.reservecopy >/dev/null 2>&1 || true; fi",
                "fi",
                "",
            ]

        lines += [
            "if command -v restorecon >/dev/null 2>&1; then restorecon -RF /data/system/users >/dev/null 2>&1 || true; fi",
            "if command -v restorecon >/dev/null 2>&1; then restorecon -RF /data/system/appops >/dev/null 2>&1 || true; fi",
            "if command -v restorecon >/dev/null 2>&1; then restorecon -RF /data/misc_de >/dev/null 2>&1 || true; fi",
            "sync",
            "exit",
            "exit",
            "",
        ]
        self.adb.shell_script(
            "\n".join(lines),
            critical=True,
            phase="restore: permission state file fixups",
            reason="could not restore permission state file owners/contexts",
        )

    def _keystore_per_uid_fixup(self, merged_sqlite_local_path: Path) -> None:
        """Replace /data/misc/keystore/persistent.sqlite with a host-side merged
        copy that contains the snapshot's per-UID rows folded into the live DB.

        Caller is responsible for producing the merged file via
        snaptool.keystore_merge.merge_rows_into_db. We stop keystore2/credstore,
        cp the merged file into place with correct owner/perms/SELinux context,
        and restart the services.
        """
        self.logger.info("Post-restore: per-UID keystore merge ...")

        remote_merged = "/data/local/tmp/keystore-snaptool-merged.sqlite"
        backup_remote = "/data/local/tmp/keystore-snaptool-rollback.sqlite"

        self.adb.adb(
            ["push", str(merged_sqlite_local_path), remote_merged],
            critical=True,
            phase="restore: push merged keystore DB",
            reason="could not push merged keystore DB to device",
        )

        qm = shlex.quote(remote_merged)
        qb = shlex.quote(backup_remote)

        script = f"""
su
set +e
KS_DB=/data/misc/keystore/persistent.sqlite

if command -v stop >/dev/null 2>&1; then
  stop keystore2 >/dev/null 2>&1 || true
  stop credstore >/dev/null 2>&1 || true
fi
if command -v setprop >/dev/null 2>&1; then
  setprop ctl.stop keystore2 >/dev/null 2>&1 || true
  setprop ctl.stop credstore >/dev/null 2>&1 || true
fi
sleep 1

cp -f "$KS_DB" {qb} 2>/dev/null || true
cp -f {qm} "$KS_DB"
rm -f "$KS_DB-wal" "$KS_DB-shm" 2>/dev/null || true

chown keystore:keystore "$KS_DB" 2>/dev/null || true
chmod 0600 "$KS_DB" 2>/dev/null || true
if command -v restorecon >/dev/null 2>&1; then
  restorecon -F "$KS_DB" >/dev/null 2>&1 || true
fi
sync

if command -v start >/dev/null 2>&1; then
  start keystore2 >/dev/null 2>&1 || true
  start credstore >/dev/null 2>&1 || true
fi
if command -v setprop >/dev/null 2>&1; then
  setprop ctl.start keystore2 >/dev/null 2>&1 || true
  setprop ctl.start credstore >/dev/null 2>&1 || true
fi
sleep 1

rm -f {qm} 2>/dev/null || true
exit
exit
"""
        try:
            self.adb.shell_script(
                script,
                critical=True,
                phase="restore: per-UID keystore swap",
                reason="could not apply per-UID keystore merge on device",
            )
        finally:
            self._restart_keystore_safety_net()

    # ---------------- NEW: keystore2 + locksettings fixups ----------------
    def _keystore_locksettings_fixups(self, device_tar: str) -> None:
        """
        If snapshot contains keystore2 + locksettings, restore them in a safe order:
        - stop keystore2 (best-effort)
        - replace /data/misc/keystore from tar (dir)
        - replace /data/system/locksettings.db* from tar
        - restorecon + perms/owners
        - start keystore2 (best-effort)

        This helps when accounts/app tokens are encrypted with keystore-backed material.
        """
        if self.cfg.sdk_version is None:
            self.logger.warning(
                "SDK version could not be determined; skipping keystore/locksettings "
                "restore for safety (fail closed)."
            )
            return
        if self.cfg.sdk_version >= 34:
            self.logger.info(
                "Skipping keystore/locksettings restore: Android 14+ (SDK %d) "
                "hardware-bound keys are not portable across device/boot sessions.",
                self.cfg.sdk_version,
            )
            return

        self.logger.info("Post-restore: Keystore2 + locksettings replace + fixups ...")

        dt = shlex.quote(device_tar)

        lines = ["su", "cd /", ""]

        # Helper: stop/start keystore2 best-effort.
        lines += [
            "# Stop keystore2 so we can safely replace its DB (best-effort)",
            "if command -v stop >/dev/null 2>&1; then",
            "  stop keystore2 >/dev/null 2>&1 || true",
            "  stop credstore >/dev/null 2>&1 || true",
            "fi",
            "if command -v setprop >/dev/null 2>&1; then",
            "  setprop ctl.stop keystore2 >/dev/null 2>&1 || true",
            "  setprop ctl.stop credstore >/dev/null 2>&1 || true",
            "fi",
            "sleep 0.5",
            "",
        ]

        # Restore /data/misc/keystore (directory) if present in tar.
        # We anchor on persistent.sqlite, but extract the whole directory for completeness.
        lines += [
            f"if tar -tf {dt} data/misc/keystore/persistent.sqlite >/dev/null 2>&1; then",
            "  # Clear existing dir contents then extract snapshot version",
            "  mkdir -p /data/misc/keystore >/dev/null 2>&1 || true",
            "  rm -f /data/misc/keystore/* >/dev/null 2>&1 || true",
            f"  tar -xpf {dt} data/misc/keystore >/dev/null 2>&1 || true",
            "  chown -R keystore:keystore /data/misc/keystore >/dev/null 2>&1 || true",
            "  chmod 700 /data/misc/keystore >/dev/null 2>&1 || true",
            "  chmod 600 /data/misc/keystore/* >/dev/null 2>&1 || true",
            "  if command -v restorecon >/dev/null 2>&1; then restorecon -RF /data/misc/keystore >/dev/null 2>&1 || true; fi",
            "fi",
            "",
        ]

        # Restore /data/system/locksettings.db* if present in tar
        # (we probe each file before extracting to avoid tar errors for missing members)
        lines += [
            "LS_LIST=''",
            f"for f in data/system/locksettings.db data/system/locksettings.db-wal data/system/locksettings.db-shm data/system/locksettings.db-journal; do",
            f"  if tar -tf {dt} \"$f\" >/dev/null 2>&1; then LS_LIST=\"$LS_LIST $f\"; fi",
            "done",
            "if [ -n \"$LS_LIST\" ]; then",
            "  rm -f /data/system/locksettings.db* >/dev/null 2>&1 || true",
            f"  tar -xpf {dt} $LS_LIST >/dev/null 2>&1 || true",
            "  chown system:system /data/system/locksettings.db* >/dev/null 2>&1 || true",
            "  chmod 600 /data/system/locksettings.db* >/dev/null 2>&1 || true",
            "  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system/locksettings.db* >/dev/null 2>&1 || true; fi",
            "fi",
            "",
        ]

        # Start keystore2 back (best-effort)
        lines += [
            "sync",
            "# Start keystore2 back (best-effort)",
            "if command -v start >/dev/null 2>&1; then",
            "  start keystore2 >/dev/null 2>&1 || true",
            "  start credstore >/dev/null 2>&1 || true",
            "fi",
            "if command -v setprop >/dev/null 2>&1; then",
            "  setprop ctl.start keystore2 >/dev/null 2>&1 || true",
            "  setprop ctl.start credstore >/dev/null 2>&1 || true",
            "fi",
            "sleep 0.5",
            "",
            "exit",
            "exit",
            "",
        ]

        try:
            self.adb.shell_script(
                "\n".join(lines),
                critical=True,
                phase="restore: keystore/locksettings fixups",
                reason="could not restore keystore/locksettings on device",
            )
        finally:
            self._restart_keystore_safety_net()

    def exec_restore_path(
        self,
        plan: "RestorePlan",
        tar_index: "TarIndex",
        local_tar,
        runtime_state: dict | None = None,
        runtime_apply_revokes: bool = False,
        device_tar: str = "/data/local/tmp/restore.tar",
        keystore_merged_local_path: Path | None = None,
        restore_state: RestoreState | None = None,
    ) -> None:
        ch = self.cfg.chunk_size

        self.adb.ensure_device_online(phase="restore-path: preflight")
        self.logger.info("Pushing temp tar to device...")
        self.adb.adb(
            ["push", str(local_tar), device_tar],
            critical=True,
            phase="restore-path: push tar",
            reason="could not push restore tar to device",
        )

        if restore_state is not None:
            restore_state.begin()

        # ---------------- Stage 1: media/files first ----------------
        media_bak_map = "/data/local/tmp/media_bak_map.txt"
        if plan.media_paths:
            self.logger.info("Stage 1/2: Restoring files/media FIRST... (%d paths)", len(plan.media_paths))

        for i in range(0, len(plan.media_paths), ch):
            chunk_paths = plan.media_paths[i:i + ch]
            chunk_no = i // ch + 1
            self.logger.info("[Stage 1] Extracting chunk %d (%d paths)...", chunk_no, len(chunk_paths))

            prep_lines = []
            map_lines = []

            for p in chunk_paths:
                parsed = self._parse_uid_pkg_from_path(p)
                if parsed:
                    uid2, pkg = parsed
                    prep_lines.append(f'am force-stop --user {uid2} {shlex.quote(pkg)} >/dev/null 2>&1 || true')

                root_abs = "/" + p
                bak_abs = root_abs + ".bak_restore6"
                expect = "0" if self._is_media_root_allow_empty(p) else "1"
                map_lines.append(f"{root_abs}|{bak_abs}|{expect}")

            map_payload = "\n".join(map_lines) + "\n"
            self.adb.shell_script(
                f"su\ncat > {shlex.quote(media_bak_map)} <<'EOF'\n{map_payload}EOF\nexit\nexit\n",
                critical=True,
                phase=f"restore-path: write media bak-map (chunk {chunk_no})",
                reason="could not write media restore map to device",
            )

            prep_blob = "\n".join(prep_lines)
            script = f"""
su
cd /
{prep_blob}
if [ -f {shlex.quote(media_bak_map)} ]; then
  while IFS='|' read -r ROOT BAK EXPECT; do
    [ -z "$ROOT" ] && continue

    if [ -e "$ROOT" ]; then
      rm -rf "$BAK" >/dev/null 2>&1 || true
      mv "$ROOT" "$BAK" >/dev/null 2>&1 || true
    fi

    tar -xpf {device_tar} "${{ROOT#/}}" >/dev/null 2>&1 || true

    if [ "$EXPECT" = "1" ]; then
      if find "$ROOT" -type f -maxdepth 6 2>/dev/null | head -n 1 | grep -q .; then
        rm -rf "$BAK" >/dev/null 2>&1 || true
      else
        rm -rf "$ROOT" >/dev/null 2>&1 || true
        if [ -d "$BAK" ]; then
          mv "$BAK" "$ROOT" >/dev/null 2>&1 || true
        fi
      fi
    else
      if [ -e "$ROOT" ]; then
        rm -rf "$BAK" >/dev/null 2>&1 || true
      else
        if [ -d "$BAK" ]; then
          mv "$BAK" "$ROOT" >/dev/null 2>&1 || true
        fi
      fi
    fi
  done < {shlex.quote(media_bak_map)}
fi
exit
exit
"""
            self.adb.shell_script(
                script,
                critical=True,
                phase=f"restore-path: extract media chunk {chunk_no}",
                reason="could not extract media chunk on device",
            )

        if restore_state is not None and plan.media_paths:
            restore_state.update_phase("media_extracted")

        # ---------------- Stage 2: apps after files ----------------
        if plan.app_paths:
            self.logger.info("Stage 2/2: Restoring apps AFTER files... (%d paths)", len(plan.app_paths))

        unique_pairs = []
        seen = set()
        for p in plan.app_paths:
            parsed = self._parse_uid_pkg_from_path(p)
            if not parsed:
                continue
            if parsed not in seen:
                seen.add(parsed)
                unique_pairs.append(parsed)

        if unique_pairs:
            lines = ["su"]
            for uid2, pkg in unique_pairs:
                lines.append(f'am force-stop --user {uid2} {shlex.quote(pkg)} >/dev/null 2>&1 || true')
            lines += ["exit", "exit"]
            self.adb.shell_script(
                "\n".join(lines) + "\n",
                critical=True,
                phase="restore-path: force-stop apps before extraction",
                reason="could not stop apps before extraction (extraction would race with running apps)",
            )

        # Replay runtime permissions/appops before framework stop/start so restore
        # is not blocked by lock-screen state after restart.
        if runtime_state:
            self.logger.info("Pre-stage: applying runtime state before framework restart ...")
            self._apply_runtime_state(
                runtime_state,
                package_batch_size=self.cfg.runtime_state_batch_size_path,
                apply_revokes=runtime_apply_revokes,
            )

        with self._framework_stopped():
            for i in range(0, len(plan.app_paths), ch):
                chunk_paths = plan.app_paths[i:i + ch]
                chunk_no = i // ch + 1
                self.logger.info("[Stage 2] Extracting chunk %d (%d paths)...", chunk_no, len(chunk_paths))

                prep_lines = []
                for p in chunk_paths:
                    parsed = self._parse_uid_pkg_from_path(p)
                    if not parsed:
                        continue
                    uid2, pkg = parsed
                    if p.startswith("data/user/") or p.startswith("data/user_de/"):
                        prep_lines.append(f'rm -rf /data/user/{uid2}/{shlex.quote(pkg)} >/dev/null 2>&1 || true')
                        prep_lines.append(f'rm -rf /data/user_de/{uid2}/{shlex.quote(pkg)} >/dev/null 2>&1 || true')

                joined = " ".join(shlex.quote(p) for p in chunk_paths)
                script = f"""
su
cd /
{chr(10).join(prep_lines)}
tar -xpf {device_tar} {joined} || true
exit
exit
"""
                self.adb.shell_script(
                    script,
                    critical=True,
                    phase=f"restore-path: extract app chunk {chunk_no}",
                    reason="could not extract app data chunk on device",
                )

            if restore_state is not None and plan.app_paths:
                restore_state.update_phase("apps_extracted")

            # Per-UID keystore merge takes precedence over the legacy whole-DB tar
            # extraction. Newer snapshots ship keystore_rows.json; older ones still
            # rely on /data/misc/keystore inside the tar (SDK <34 only).
            if keystore_merged_local_path is not None:
                self._keystore_per_uid_fixup(keystore_merged_local_path)
            else:
                self._keystore_locksettings_fixups(device_tar)
            if restore_state is not None:
                restore_state.update_phase("keystore_done")

            # AccountManager DB replace + perms/contexts
            self._accountmanager_fixups(plan.user_ids, device_tar)
            if restore_state is not None:
                restore_state.update_phase("accountmgr_done")

            self._permission_state_file_fixups(plan.user_ids)
            if restore_state is not None:
                restore_state.update_phase("perm_fixups_done")

            self.logger.info("Post-stage: restorecon /data/user /data/user_de ...")
            self.adb.shell_script(
                "su\nsync\n"
                "if command -v restorecon >/dev/null 2>&1; then restorecon -RF /data/user /data/user_de >/dev/null 2>&1 || true; fi\n"
                "exit\nexit\n",
                critical=True,
                phase="restore-path: restorecon /data/user",
                reason="could not restore SELinux contexts on /data/user (apps would be unable to read their data)",
            )
            if restore_state is not None:
                restore_state.update_phase("restorecon_done")

        # `with _framework_stopped()` has exited cleanly → framework restart
        # already ran. Mark it so an aborted post-restore phase still tells
        # the operator the framework is up.
        if restore_state is not None:
            restore_state.update_phase("framework_restarted")

        if runtime_state:
            self.logger.info("Post-stage: re-applying runtime state after framework restart ...")
            self._apply_runtime_state(
                runtime_state,
                package_batch_size=self.cfg.runtime_state_batch_size_path,
                apply_revokes=runtime_apply_revokes,
            )

        # Media owner/SELinux fixup after framework restart.
        fix_lines = ["su", "cd /"]
        for uid in plan.user_ids:
            fix_lines.append(f'chown -R media_rw:media_rw /data/media/{uid} >/dev/null 2>&1 || true')
            fix_lines.append(
                'if command -v restorecon >/dev/null 2>&1; then '
                f'restorecon -RF /data/media/{uid} >/dev/null 2>&1 || true; '
                'fi'
            )
            fix_lines.append(f'am force-stop --user {uid} com.android.providers.media >/dev/null 2>&1 || true')
            fix_lines.append(f'am force-stop --user {uid} com.google.android.apps.photos >/dev/null 2>&1 || true')
        fix_lines += ["exit", "exit"]
        self.adb.shell_script(
            "\n".join(fix_lines) + "\n",
            critical=True,
            phase="restore-path: media owner/SELinux fixup",
            reason="could not restore media ownership/SELinux contexts (apps would be unable to read media)",
        )
        if restore_state is not None:
            restore_state.update_phase("media_owner_done")

        # Photos permissions (best-effort: idempotent, app-level).
        perm = ["su", "set -e", ""]
        for uid in plan.user_ids:
            perm += [
                f'pm grant --user {uid} {plan.photos_pkg} android.permission.READ_MEDIA_IMAGES >/dev/null 2>&1 || true',
                f'pm grant --user {uid} {plan.photos_pkg} android.permission.READ_MEDIA_VIDEO >/dev/null 2>&1 || true',
                f'pm grant --user {uid} {plan.photos_pkg} android.permission.READ_EXTERNAL_STORAGE >/dev/null 2>&1 || true',
            ]
        perm += ["exit", "exit"]
        self.adb.shell_script(
            "\n".join(perm) + "\n",
            critical=False,
            phase="restore-path: photos permissions (best-effort)",
        )

        # Ensure SystemUI not stopped (best-effort: re-runnable, idempotent).
        ui = ["su"]
        for uid in plan.user_ids:
            ui += [
                f'pm enable --user {uid} {plan.systemui_pkg} >/dev/null 2>&1 || true',
                f'cmd package set-stopped-state --user {uid} {plan.systemui_pkg} false >/dev/null 2>&1 || true',
                f'am set-stopped-state --user {uid} {plan.systemui_pkg} false >/dev/null 2>&1 || true',
            ]
        ui += ["exit", "exit"]
        self.adb.shell_script(
            "\n".join(ui) + "\n",
            critical=False,
            phase="restore-path: ensure SystemUI enabled (best-effort)",
        )

        # Safe refresh (best-effort).
        self._safe_media_refresh(plan)

        # Cleanup device tar (best-effort).
        self.adb.shell_root(f"rm -f {shlex.quote(device_tar)}", check=False)

    def exec_restore_app(
        self,
        package: str,
        user_ids: list[int],
        local_tar,
        auth_pkgs: list[str] | None = None,
        include_account_db: bool = True,
        present_roots: set[str] | None = None,
        runtime_state: dict | None = None,
        device_tar: str = "/data/local/tmp/restore-app.tar",
        keystore_merged_local_path: Path | None = None,
    ) -> None:
        if not user_ids:
            self.logger.warning("No users supplied for app restore; nothing to do.")
            return

        pkgs: list[str] = []
        seen = set()
        for p in [package] + list(auth_pkgs or []):
            if p and p not in seen:
                seen.add(p)
                pkgs.append(p)

        app_paths: list[str] = []
        for uid in user_ids:
            for pkg in pkgs:
                app_paths.extend(self._build_pkg_roots(uid, pkg))

        if present_roots is not None:
            app_paths = [p for p in app_paths if p in present_roots]
        app_paths = list(dict.fromkeys(app_paths))

        ch = self.cfg.chunk_size
        self.logger.info(
            "Restoring app snapshot: package=%s users=%s packages=%d roots=%d account_db=%s",
            package,
            ",".join(str(u) for u in user_ids),
            len(pkgs),
            len(app_paths),
            include_account_db,
        )
        self.adb.ensure_device_online(phase="restore-app: preflight")
        self.logger.info("Pushing temp tar to device...")
        self.adb.adb(
            ["push", str(local_tar), device_tar],
            critical=True,
            phase="restore-app: push tar",
            reason="could not push restore tar to device",
        )

        all_pairs = []
        all_seen = set()
        for p in app_paths:
            parsed = self._parse_uid_pkg_from_path(p)
            if parsed and parsed not in all_seen:
                all_seen.add(parsed)
                all_pairs.append(parsed)

        if all_pairs:
            force_lines = ["su"]
            for uid, pkg in all_pairs:
                force_lines.append(f'am force-stop --user {uid} {shlex.quote(pkg)} >/dev/null 2>&1 || true')
            force_lines += ["exit", "exit"]
            self.adb.shell_script(
                "\n".join(force_lines) + "\n",
                critical=True,
                phase="restore-app: force-stop apps before extraction",
                reason="could not stop apps before extraction (extraction would race with running apps)",
            )
        else:
            self.logger.warning("No app data roots from snapshot match requested package/auth packages.")

        if runtime_state:
            self.logger.info("Pre-stage: applying runtime state before framework restart ...")
            self._apply_runtime_state(
                runtime_state,
                package_batch_size=self.cfg.runtime_state_batch_size_app,
                apply_revokes=True,
            )

        from contextlib import nullcontext
        framework_ctx = self._framework_stopped() if include_account_db else nullcontext()

        with framework_ctx:
            for i in range(0, len(app_paths), ch):
                chunk_paths = app_paths[i:i + ch]
                chunk_no = i // ch + 1
                self.logger.info("App restore chunk %d (%d paths)...", chunk_no, len(chunk_paths))

                unique_pairs = []
                seen_pairs = set()
                for p in chunk_paths:
                    parsed = self._parse_uid_pkg_from_path(p)
                    if parsed and parsed not in seen_pairs:
                        seen_pairs.add(parsed)
                        unique_pairs.append(parsed)

                prep_lines = []
                fix_owner_lines = []
                fix_ctx_lines = []
                owner_idx = 0
                ctx_idx = 0
                for uid2, pkg in unique_pairs:
                    owner_var = f"O{owner_idx}"
                    owner_idx += 1
                    ctx_var = f"C{ctx_idx}"
                    ctx_idx += 1
                    quoted_pkg = shlex.quote(pkg)
                    prep_lines += [
                        # Capture current app UID:GID before deletion so restored files keep app ownership.
                        f'{owner_var}="$(stat -c \'%u:%g\' /data/user/{uid2}/{quoted_pkg} 2>/dev/null || stat -c \'%u:%g\' /data/user_de/{uid2}/{quoted_pkg} 2>/dev/null || true)"',
                        f'if [ -z "${owner_var}" ] && [ -f /data/system/packages.list ]; then '
                        f'{owner_var}="$(awk \'$1==\\"{pkg}\\" {{print $2 ":" $2; exit}}\' /data/system/packages.list 2>/dev/null || true)"; fi',
                        # Capture current SELinux app-data label (includes category set on most builds).
                        f'{ctx_var}="$(ls -Zd /data/user/{uid2}/{quoted_pkg} 2>/dev/null | awk \'{{print $1}}\' || ls -Zd /data/user_de/{uid2}/{quoted_pkg} 2>/dev/null | awk \'{{print $1}}\' || true)"',
                        f'rm -rf /data/user/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'rm -rf /data/user_de/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'rm -rf /data/media/{uid2}/Android/data/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'rm -rf /data/media/{uid2}/Android/media/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'rm -rf /data/media/{uid2}/Android/obb/{quoted_pkg} >/dev/null 2>&1 || true',
                    ]
                    fix_owner_lines += [
                        f'if [ -n "${owner_var}" ]; then',
                        f'  chown -R "${owner_var}" /data/user/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'  chown -R "${owner_var}" /data/user_de/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'fi',
                    ]
                    fix_ctx_lines += [
                        f'if [ -n "${ctx_var}" ] && command -v chcon >/dev/null 2>&1; then',
                        f'  chcon -R "${ctx_var}" /data/user/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'  chcon -R "${ctx_var}" /data/user_de/{uid2}/{quoted_pkg} >/dev/null 2>&1 || true',
                        f'fi',
                    ]

                joined = " ".join(shlex.quote(p) for p in chunk_paths)
                script = f"""
su
cd /
{chr(10).join(prep_lines)}
tar -xpf {device_tar} {joined} >/dev/null 2>&1 || true
{chr(10).join(fix_owner_lines)}
{chr(10).join(fix_ctx_lines)}
exit
exit
"""
                self.adb.shell_script(
                    script,
                    critical=True,
                    phase=f"restore-app: extract chunk {chunk_no}",
                    reason="could not extract app data chunk on device",
                )

            if include_account_db:
                if keystore_merged_local_path is not None:
                    self._keystore_per_uid_fixup(keystore_merged_local_path)
                else:
                    self._keystore_locksettings_fixups(device_tar)
                self._accountmanager_fixups(user_ids, device_tar)

            restorecon_lines = ["su", "sync"]
            restorecon_lines.append("if command -v restorecon >/dev/null 2>&1; then")
            for uid in user_ids:
                for pkg in pkgs:
                    restorecon_lines += [
                        f'  restorecon -RF /data/user/{uid}/{shlex.quote(pkg)} >/dev/null 2>&1 || true',
                        f'  restorecon -RF /data/user_de/{uid}/{shlex.quote(pkg)} >/dev/null 2>&1 || true',
                        f'  restorecon -RF /data/media/{uid}/Android/data/{shlex.quote(pkg)} >/dev/null 2>&1 || true',
                        f'  restorecon -RF /data/media/{uid}/Android/media/{shlex.quote(pkg)} >/dev/null 2>&1 || true',
                        f'  restorecon -RF /data/media/{uid}/Android/obb/{shlex.quote(pkg)} >/dev/null 2>&1 || true',
                    ]
            restorecon_lines += ["fi", "exit", "exit", ""]
            self.adb.shell_script(
                "\n".join(restorecon_lines),
                critical=True,
                phase="restore-app: restorecon app dirs",
                reason="could not restore SELinux contexts on app data (apps would be unable to read their data)",
            )

        if runtime_state:
            self.logger.info("Post-stage: re-applying runtime state after framework restart ...")
            self._apply_runtime_state(
                runtime_state,
                package_batch_size=self.cfg.runtime_state_batch_size_app,
                apply_revokes=True,
            )

        self.adb.shell_root(f"rm -f {shlex.quote(device_tar)}", check=False)

    def exec_restore_full(self, device_tar: str) -> None:
        # WARNING: This method bypasses _keystore_locksettings_fixups() entirely —
        # it untars /data directly. Do NOT re-enable without adding the SDK >= 34
        # guard to exclude keystore/locksettings from extraction.
        script = f"""
su
cd /
tar -xpf {device_tar} data || true
exit
exit
"""
        self.adb.shell_script(
            script,
            critical=True,
            phase="restore-full: extract /data",
            reason="could not extract /data on device",
        )

    def _accountmanager_fixups(self, user_ids: list[int], device_tar: str) -> None:
        """
        AccountManager support:
        Replace AccountManager DBs from backup tar and ensure correct owner/perms/SELinux context.

        Required files (per user in tar):
        data/system_ce/<uid>/accounts_ce.db*
        data/system_de/<uid>/accounts_de.db*
        """
        self.logger.info("Post-restore: AccountManager DB replace + fixups ...")
        dt = shlex.quote(device_tar)

        lines = ["su", "cd /", ""]

        for uid in user_ids:
            lines += [
                f"if tar -tf {dt} data/system_ce/{uid}/accounts_ce.db >/dev/null 2>&1; then",
                f"  rm -f /data/system_ce/{uid}/accounts_ce.db* >/dev/null 2>&1 || true",
                f"  tar -xpf {dt} "
                f"data/system_ce/{uid}/accounts_ce.db "
                f"data/system_ce/{uid}/accounts_ce.db-wal "
                f"data/system_ce/{uid}/accounts_ce.db-shm "
                f">/dev/null 2>&1 || true",
                f"  chown system:system /data/system_ce/{uid}/accounts_ce.db* >/dev/null 2>&1 || true",
                f"  chmod 600 /data/system_ce/{uid}/accounts_ce.db* >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system_ce/{uid}/accounts_ce.db* >/dev/null 2>&1 || true; fi",
                f"fi",
                "",
            ]

            lines += [
                f"if tar -tf {dt} data/system_de/{uid}/accounts_de.db >/dev/null 2>&1; then",
                f"  rm -f /data/system_de/{uid}/accounts_de.db* >/dev/null 2>&1 || true",
                f"  tar -xpf {dt} "
                f"data/system_de/{uid}/accounts_de.db "
                f"data/system_de/{uid}/accounts_de.db-wal "
                f"data/system_de/{uid}/accounts_de.db-shm "
                f">/dev/null 2>&1 || true",
                f"  chown system:system /data/system_de/{uid}/accounts_de.db* >/dev/null 2>&1 || true",
                f"  chmod 600 /data/system_de/{uid}/accounts_de.db* >/dev/null 2>&1 || true",
                f"  if command -v restorecon >/dev/null 2>&1; then restorecon -v /data/system_de/{uid}/accounts_de.db* >/dev/null 2>&1 || true; fi",
                f"fi",
                "",
            ]

        lines += ["sync", "exit", "exit", ""]
        self.adb.shell_script(
            "\n".join(lines),
            critical=True,
            phase="restore: accountmanager DB swap",
            reason="could not replace AccountManager DBs on device",
        )
